### ISSUE TITLE
elogind with cinnamon

### ISSUE THREAD

**Issue by cromerc** [cromnix/artix#7]
elogind is not working correctly under cinnamon. When the shutdown or restart buttons are clicked all it does is close the session, and in this case return to lightdm.

**Comment by udeved** [comment]
Did you have ck installed before?
Iirc, cinnamon has two logind keys in dconf, that might still be disabled for ck?

**Comment by cromerc** [comment]
Yes I did have ck installed before I did the convert to artix. However when I did the convert I removed ck and I also changed the dconf to use logind under cinnamon, so that isn't the problem here.

**Comment by cromerc** [comment]
Found the problem, it was polkit. I still had "polkit-consolekit" left over in my system after the upgrade. After replacing it with polkit from world it is now fixed.
